/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.ApiResponseFailure;
import io.swagger.model.ApiResponseSuccess;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-14T18:02:50.529Z")

@Api(value = "command", description = "the command API")
@RequestMapping(value = "")
public interface CommandApi {

    @ApiOperation(value = "Starts multiple commands in blocking mode sequentially. Set the client timeout at needed value.", nickname = "commandPost", notes = "", response = ApiResponseSuccess.class, tags = {"estuary-testrunner",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "commands start success", response = ApiResponseSuccess.class),
            @ApiResponse(code = 404, message = "commands start failure", response = ApiResponseFailure.class)})
    @RequestMapping(value = "/command",
            produces = {"application/json"},
            consumes = {"text/plain"},
            method = RequestMethod.POST)
    default ResponseEntity<ApiResponseSuccess> commandPost(@ApiParam(value = "Commands to run. E.g. ls -lrt", required = true) @Valid @RequestBody String commands, @ApiParam(value = "") @RequestHeader(value = "Token", required = false) String token) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
