/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.ApiResponseFailure;
import io.swagger.model.ApiResponseSuccess;
import io.swagger.model.Filecontent;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-14T18:02:50.529Z")

@Api(value = "file", description = "the file API")
@RequestMapping(value = "")
public interface FileApi {

    @ApiOperation(value = "Gets the content of the file", nickname = "fileGet", notes = "", response = ApiResponseSuccess.class, tags = {"estuary-testrunner",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The content of the file in plain text, success", response = ApiResponseSuccess.class),
            @ApiResponse(code = 404, message = "Failure, the file content could not be read", response = ApiResponseFailure.class)})
    @RequestMapping(value = "/file",
            produces = {"application/json"},
            consumes = {"application/json", "application/x-www-form-urlencoded"},
            method = RequestMethod.GET)
    default ResponseEntity<ApiResponseSuccess> fileGet(@ApiParam(value = "") @RequestHeader(value = "Token", required = false) String token, @ApiParam(value = "Target file path to get") @RequestHeader(value = "File-Path", required = false) String filePath) {

        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Uploads a file no mater the format. Binary or raw", nickname = "filePut", notes = "", response = ApiResponseSuccess.class, tags = {"estuary-testrunner",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The content of the file was uploaded successfully", response = ApiResponseSuccess.class),
            @ApiResponse(code = 404, message = "Failure, the file content could not be uploaded", response = ApiResponseFailure.class)})
    @RequestMapping(value = "/file",
            produces = {"application/json"},
            consumes = {"application/json", "application/x-www-form-urlencoded"},
            method = RequestMethod.PUT)
    default ResponseEntity<ApiResponseSuccess> filePut(@ApiParam(value = "The content of the file", required = true) @Valid @RequestBody Filecontent content, @ApiParam(value = "", required = true) @RequestHeader(value = "File-Path", required = true) String filePath, @ApiParam(value = "") @RequestHeader(value = "Token", required = false) String token) {

        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
