/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.ApiResponseFailure;
import io.swagger.model.ApiResponseSuccess;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-14T18:02:50.529Z")

@Api(value = "folder", description = "the folder API")
@RequestMapping(value = "")
public interface FolderApi {

    @ApiOperation(value = "Gets the folder as zip archive. Useful to get test results folder", nickname = "folderGet", notes = "", response = ApiResponseSuccess.class, tags = {"estuary-testrunner",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The content of the folder as zip archive", response = ApiResponseSuccess.class),
            @ApiResponse(code = 404, message = "The content of the folder could not be obtained", response = ApiResponseFailure.class)})
    @RequestMapping(value = "/folder",
            produces = {"application/zip"},
            consumes = {"application/json", "application/x-www-form-urlencoded"},
            method = RequestMethod.GET)
    default ResponseEntity<ApiResponseSuccess> folderGet(@ApiParam(value = "Target folder path to get as zip", required = true) @RequestHeader(value = "Folder-Path", required = true) String folderPath, @ApiParam(value = "") @RequestHeader(value = "Token", required = false) String token) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
