/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.ApiResponseSuccess;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-14T18:02:50.529Z")

@Api(value = "ping", description = "the ping API")
@RequestMapping(value = "")
public interface PingApi {

    @ApiOperation(value = "Ping endpoint which replies with pong", nickname = "pingGet", notes = "", response = ApiResponseSuccess.class, tags = {"estuary-testrunner",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Ping endpoint which replies with pong. Useful when checking the alive status of the service", response = ApiResponseSuccess.class)})
    @RequestMapping(value = "/ping",
            produces = {"application/json"},
            method = RequestMethod.GET)
    default ResponseEntity<ApiResponseSuccess> pingGet(@ApiParam(value = "") @RequestHeader(value = "Token", required = false) String token) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
